/**
 * Page- and query-level search fixtures for Summit & Sage.
 *
 * These are constrained rather than invented. Session and confirmed-booking totals across pages
 * reconcile exactly to the workspace weekly observations in `flagshipComparisons`, because those
 * come from the same analytics property and must agree.
 *
 * Search Console rows deliberately do not reconcile exactly. Google withholds anonymised queries
 * and thresholds low-volume rows, so page and query clicks sum to less than the property total.
 * Modelling that gap — rather than making the arithmetic tidy — is what lets ReachOps show a
 * coverage note instead of quietly implying complete data.
 *
 * The AC repair page carries the flagship divergence and therefore reuses the exact session and
 * booking values already published as EV-104 and EV-105. No surface may restate those numbers
 * from a second source.
 */

export interface SearchPageFixture {
  /** Uppercase evidence-safe key. Evidence IDs are derived from it. */
  key: string;
  path: string;
  title: string;
  metaDescription: string;
  /** Which service line the page belongs to, used for grouping and campaign filters. */
  serviceLine: 'AIR_CONDITIONING' | 'WATER_HEATERS' | 'PLUMBING' | 'ELECTRICAL' | 'COMPANY';
  priorClicks: number;
  currentClicks: number;
  priorImpressions: number;
  currentImpressions: number;
  priorPosition: number;
  currentPosition: number;
  priorSessions: number;
  currentSessions: number;
  priorBookings: number;
  currentBookings: number;
}

export const searchPages: SearchPageFixture[] = [
  {
    key: 'AC-REPAIR',
    path: '/air-conditioning/repair',
    title: 'AC Repair in Denver | Same-Day Service | Summit & Sage',
    metaDescription:
      'Denver AC repair with same-day appointments and upfront pricing. Licensed technicians, no overtime charges.',
    serviceLine: 'AIR_CONDITIONING',
    priorClicks: 900,
    currentClicks: 1180,
    priorImpressions: 18900,
    currentImpressions: 24800,
    priorPosition: 6.8,
    currentPosition: 6.2,
    priorSessions: 1148,
    currentSessions: 1505,
    priorBookings: 70,
    currentBookings: 59,
  },
  {
    key: 'HOME',
    path: '/',
    title: 'Summit & Sage Home Services | Denver HVAC, Plumbing & Electrical',
    metaDescription:
      'Denver-area heating, cooling, plumbing and electrical service. Book online in under two minutes.',
    serviceLine: 'COMPANY',
    priorClicks: 905,
    currentClicks: 940,
    priorImpressions: 17800,
    currentImpressions: 18600,
    priorPosition: 4.3,
    currentPosition: 4.1,
    priorSessions: 1810,
    currentSessions: 1880,
    priorBookings: 30,
    currentBookings: 31,
  },
  {
    key: 'AC-REPLACEMENT',
    path: '/air-conditioning/replacement',
    title: 'AC Replacement & Installation Denver | Summit & Sage',
    metaDescription:
      'High-efficiency AC replacement for Denver homes. Free in-home estimate and financing options.',
    serviceLine: 'AIR_CONDITIONING',
    priorClicks: 660,
    currentClicks: 720,
    priorImpressions: 19600,
    currentImpressions: 21400,
    priorPosition: 9.1,
    currentPosition: 8.8,
    priorSessions: 840,
    currentSessions: 905,
    priorBookings: 22,
    currentBookings: 24,
  },
  {
    key: 'AC-MAINTENANCE',
    path: '/air-conditioning/maintenance',
    title: 'AC Tune-Up & Maintenance Denver | Summit & Sage',
    metaDescription:
      'Seasonal AC tune-ups that keep cooling costs down. Included with Comfort Club membership.',
    serviceLine: 'AIR_CONDITIONING',
    priorClicks: 575,
    currentClicks: 610,
    priorImpressions: 14100,
    currentImpressions: 14900,
    priorPosition: 7.6,
    currentPosition: 7.4,
    priorSessions: 720,
    currentSessions: 760,
    priorBookings: 17,
    currentBookings: 18,
  },
  {
    key: 'WATER-HEATER-GUIDE',
    path: '/water-heaters/repair-or-replace',
    title: 'Repair or Replace Your Water Heater? A Denver Homeowner Guide',
    metaDescription:
      'Compare water-heater repair and replacement costs, lifespan and efficiency for Denver homes.',
    serviceLine: 'WATER_HEATERS',
    priorClicks: 840,
    currentClicks: 880,
    priorImpressions: 18300,
    currentImpressions: 19200,
    priorPosition: 5.8,
    currentPosition: 5.6,
    priorSessions: 975,
    currentSessions: 1020,
    priorBookings: 20,
    currentBookings: 21,
  },
  {
    key: 'TANKLESS',
    path: '/water-heaters/tankless',
    title: 'Tankless Water Heater Installation Denver | Summit & Sage',
    metaDescription:
      'Tankless water heater installation and sizing for Denver homes, with rebate guidance.',
    serviceLine: 'WATER_HEATERS',
    priorClicks: 395,
    currentClicks: 430,
    priorImpressions: 15200,
    currentImpressions: 16800,
    priorPosition: 11.6,
    currentPosition: 11.2,
    priorSessions: 495,
    currentSessions: 540,
    priorBookings: 10,
    currentBookings: 11,
  },
  {
    key: 'DRAIN-CLEANING',
    path: '/plumbing/drain-cleaning',
    title: 'Drain Cleaning Denver | Summit & Sage Plumbing',
    metaDescription:
      'Professional drain cleaning and camera inspection across the Denver metro. Same-day slots.',
    serviceLine: 'PLUMBING',
    priorClicks: 665,
    currentClicks: 690,
    priorImpressions: 14800,
    currentImpressions: 15400,
    priorPosition: 8.1,
    currentPosition: 7.9,
    priorSessions: 785,
    currentSessions: 815,
    priorBookings: 21,
    currentBookings: 22,
  },
  {
    key: 'EMERGENCY-PLUMBING',
    path: '/plumbing/emergency',
    title: '24/7 Emergency Plumber Denver | Summit & Sage',
    metaDescription:
      'Burst pipes, major leaks and no-water emergencies. Denver emergency plumbers on call.',
    serviceLine: 'PLUMBING',
    priorClicks: 495,
    currentClicks: 520,
    priorImpressions: 13100,
    currentImpressions: 13700,
    priorPosition: 9.6,
    currentPosition: 9.3,
    priorSessions: 610,
    currentSessions: 640,
    priorBookings: 18,
    currentBookings: 19,
  },
  {
    key: 'PANEL-UPGRADE',
    path: '/electrical/panel-upgrade',
    title: 'Electrical Panel Upgrades Denver | Summit & Sage',
    metaDescription:
      '100A to 200A electrical panel upgrades for older Denver homes. Permitting handled.',
    serviceLine: 'ELECTRICAL',
    priorClicks: 450,
    currentClicks: 480,
    priorImpressions: 16400,
    currentImpressions: 17600,
    priorPosition: 12.8,
    currentPosition: 12.4,
    priorSessions: 555,
    currentSessions: 590,
    priorBookings: 11,
    currentBookings: 12,
  },
  {
    key: 'EV-CHARGER',
    path: '/electrical/ev-charger',
    title: 'EV Charger Installation Denver | Summit & Sage Electrical',
    metaDescription:
      'Level 2 EV charger installation for Denver homes, including load calculation and permits.',
    serviceLine: 'ELECTRICAL',
    priorClicks: 280,
    currentClicks: 310,
    priorImpressions: 12900,
    currentImpressions: 14200,
    priorPosition: 15.4,
    currentPosition: 14.8,
    priorSessions: 355,
    currentSessions: 395,
    priorBookings: 6,
    currentBookings: 7,
  },
  {
    key: 'COMFORT-CLUB',
    path: '/membership/comfort-club',
    title: 'Comfort Club Maintenance Membership | Summit & Sage',
    metaDescription:
      'Priority scheduling, seasonal tune-ups and repair discounts for Denver homeowners.',
    serviceLine: 'COMPANY',
    priorClicks: 245,
    currentClicks: 260,
    priorImpressions: 6500,
    currentImpressions: 6900,
    priorPosition: 8.4,
    currentPosition: 8.1,
    priorSessions: 450,
    currentSessions: 480,
    priorBookings: 8,
    currentBookings: 9,
  },
  {
    key: 'SERVICE-AREA',
    path: '/about/service-area',
    title: 'Service Area | Denver Metro | Summit & Sage Home Services',
    metaDescription:
      'Neighbourhoods and suburbs served across the Denver metro, with typical response times.',
    serviceLine: 'COMPANY',
    priorClicks: 170,
    currentClicks: 180,
    priorImpressions: 5100,
    currentImpressions: 5400,
    priorPosition: 10.9,
    currentPosition: 10.6,
    priorSessions: 300,
    currentSessions: 320,
    priorBookings: 4,
    currentBookings: 4,
  },
  {
    key: 'BOOK',
    path: '/contact/book',
    title: 'Book an Appointment | Summit & Sage Home Services',
    metaDescription: 'Choose a service, pick an arrival window and confirm online in two minutes.',
    serviceLine: 'COMPANY',
    priorClicks: 90,
    currentClicks: 95,
    priorImpressions: 2700,
    currentImpressions: 2800,
    priorPosition: 7.0,
    currentPosition: 6.8,
    priorSessions: 437,
    currentSessions: 590,
    priorBookings: 4,
    currentBookings: 9,
  },
];

export type QueryIntent = 'INFORMATIONAL' | 'COMMERCIAL' | 'TRANSACTIONAL' | 'NAVIGATIONAL';

export interface SearchQueryFixture {
  key: string;
  query: string;
  intent: QueryIntent;
  branded: boolean;
  landingPageKey: string;
  priorClicks: number;
  currentClicks: number;
  priorImpressions: number;
  currentImpressions: number;
  priorPosition: number;
  currentPosition: number;
}

export const searchQueries: SearchQueryFixture[] = [
  // Branded demand. Strong positions, high click-through, and no opportunity to chase.
  ['Q01', 'summit and sage', 'NAVIGATIONAL', true, 'HOME', 520, 545, 5800, 6100, 1.2, 1.1],
  [
    'Q02',
    'summit & sage hvac denver',
    'NAVIGATIONAL',
    true,
    'HOME',
    210,
    225,
    2400,
    2500,
    1.4,
    1.3,
  ],
  [
    'Q03',
    'summit sage home services',
    'NAVIGATIONAL',
    true,
    'HOME',
    145,
    152,
    1700,
    1780,
    1.6,
    1.5,
  ],
  [
    'Q04',
    'comfort club membership',
    'NAVIGATIONAL',
    true,
    'COMFORT-CLUB',
    82,
    90,
    1600,
    1750,
    3.2,
    2.9,
  ],

  // AC repair cluster. Demand is climbing sharply into the Denver cooling season.
  ['Q05', 'ac repair denver', 'TRANSACTIONAL', false, 'AC-REPAIR', 480, 610, 9800, 12400, 5.8, 5.1],
  ['Q06', 'ac repair near me', 'TRANSACTIONAL', false, 'AC-REPAIR', 190, 236, 6200, 7100, 6.6, 5.9],
  [
    'Q07',
    'emergency ac repair denver',
    'TRANSACTIONAL',
    false,
    'AC-REPAIR',
    165,
    205,
    3900,
    4600,
    7.2,
    6.4,
  ],
  [
    'Q08',
    '24 hour ac repair denver',
    'TRANSACTIONAL',
    false,
    'AC-REPAIR',
    88,
    96,
    4100,
    5200,
    8.9,
    8.2,
  ],
  [
    'Q09',
    'air conditioner not cooling',
    'INFORMATIONAL',
    false,
    'AC-REPAIR',
    120,
    148,
    5600,
    6800,
    9.4,
    8.7,
  ],
  [
    'Q10',
    'swamp cooler repair denver',
    'TRANSACTIONAL',
    false,
    'AC-REPAIR',
    78,
    86,
    3100,
    3400,
    10.4,
    9.8,
  ],
  [
    'Q11',
    'furnace repair denver',
    'TRANSACTIONAL',
    false,
    'AC-REPAIR',
    96,
    88,
    4600,
    4300,
    9.2,
    9.6,
  ],

  // Replacement and the repair-versus-replace question. High exposure, weak capture.
  [
    'Q12',
    'ac replacement denver',
    'COMMERCIAL',
    false,
    'AC-REPLACEMENT',
    210,
    245,
    6400,
    7200,
    7.8,
    7.1,
  ],
  [
    'Q13',
    'ac repair vs replace',
    'INFORMATIONAL',
    false,
    'AC-REPLACEMENT',
    142,
    180,
    7100,
    8900,
    12.2,
    11.4,
  ],
  [
    'Q14',
    'what should an ac replacement cost in denver',
    'INFORMATIONAL',
    false,
    'AC-REPLACEMENT',
    64,
    71,
    5900,
    7400,
    12.6,
    11.8,
  ],
  [
    'Q15',
    'how long does an ac unit last',
    'INFORMATIONAL',
    false,
    'AC-REPLACEMENT',
    78,
    92,
    3400,
    4100,
    13.8,
    12.9,
  ],
  [
    'Q16',
    'hvac financing denver',
    'INFORMATIONAL',
    false,
    'AC-REPLACEMENT',
    52,
    58,
    2400,
    2700,
    12.8,
    12.1,
  ],

  // Maintenance and membership.
  [
    'Q17',
    'ac tune up denver',
    'COMMERCIAL',
    false,
    'AC-MAINTENANCE',
    185,
    210,
    4200,
    4800,
    6.9,
    6.4,
  ],
  [
    'Q18',
    'hvac maintenance plan denver',
    'COMMERCIAL',
    false,
    'COMFORT-CLUB',
    96,
    108,
    2300,
    2600,
    8.2,
    7.6,
  ],

  // Water heaters. The comparison guide was refreshed in March and has recovered.
  [
    'Q19',
    'water heater repair denver',
    'TRANSACTIONAL',
    false,
    'WATER-HEATER-GUIDE',
    240,
    262,
    5400,
    5900,
    5.4,
    5.0,
  ],
  [
    'Q20',
    'water heater replacement cost',
    'INFORMATIONAL',
    false,
    'WATER-HEATER-GUIDE',
    175,
    195,
    6100,
    6700,
    7.1,
    6.6,
  ],
  [
    'Q21',
    'repair or replace water heater',
    'INFORMATIONAL',
    false,
    'WATER-HEATER-GUIDE',
    168,
    188,
    4900,
    5300,
    6.2,
    5.7,
  ],
  [
    'Q22',
    'tankless water heater denver',
    'COMMERCIAL',
    false,
    'TANKLESS',
    128,
    142,
    5200,
    5800,
    11.2,
    10.6,
  ],
  [
    'Q23',
    'tankless vs tank water heater',
    'INFORMATIONAL',
    false,
    'TANKLESS',
    84,
    96,
    4400,
    4900,
    12.4,
    11.7,
  ],

  // Plumbing.
  [
    'Q24',
    'drain cleaning denver',
    'TRANSACTIONAL',
    false,
    'DRAIN-CLEANING',
    265,
    288,
    5600,
    6100,
    7.4,
    6.9,
  ],
  [
    'Q25',
    'clogged drain repair denver',
    'TRANSACTIONAL',
    false,
    'DRAIN-CLEANING',
    148,
    162,
    3800,
    4200,
    8.6,
    8.0,
  ],
  [
    'Q26',
    'emergency plumber denver',
    'TRANSACTIONAL',
    false,
    'EMERGENCY-PLUMBING',
    195,
    215,
    5100,
    5600,
    8.9,
    8.3,
  ],
  [
    'Q27',
    'burst pipe repair denver',
    'TRANSACTIONAL',
    false,
    'EMERGENCY-PLUMBING',
    92,
    104,
    2900,
    3200,
    10.2,
    9.5,
  ],
  [
    'Q28',
    'same day plumber denver',
    'TRANSACTIONAL',
    false,
    'EMERGENCY-PLUMBING',
    86,
    96,
    3300,
    3700,
    9.6,
    8.9,
  ],

  // Electrical. Newer service lines with exposure well ahead of capture.
  [
    'Q29',
    'electrical panel upgrade denver',
    'COMMERCIAL',
    false,
    'PANEL-UPGRADE',
    155,
    172,
    5900,
    6500,
    11.8,
    11.1,
  ],
  [
    'Q30',
    '200 amp panel upgrade cost',
    'INFORMATIONAL',
    false,
    'PANEL-UPGRADE',
    88,
    98,
    4200,
    4700,
    13.4,
    12.6,
  ],
  [
    'Q31',
    'ev charger installation denver',
    'COMMERCIAL',
    false,
    'EV-CHARGER',
    112,
    128,
    5100,
    5700,
    14.2,
    13.4,
  ],
  [
    'Q32',
    'tesla charger installer denver',
    'COMMERCIAL',
    false,
    'EV-CHARGER',
    62,
    72,
    2800,
    3200,
    15.6,
    14.7,
  ],

  // Company-level and comparison demand.
  ['Q33', 'hvac company denver', 'COMMERCIAL', false, 'HOME', 205, 228, 7400, 8100, 6.4, 5.9],
  ['Q34', 'best hvac denver', 'COMMERCIAL', false, 'HOME', 138, 155, 5200, 5800, 7.8, 7.2],
  [
    'Q35',
    'heating and cooling denver',
    'COMMERCIAL',
    false,
    'HOME',
    118,
    130,
    4800,
    5300,
    8.4,
    7.8,
  ],
  ['Q36', 'home services denver', 'COMMERCIAL', false, 'HOME', 74, 82, 3200, 3500, 11.2, 10.6],
  ['Q37', 'denver ac repair reviews', 'INFORMATIONAL', false, 'HOME', 64, 72, 2600, 2900, 8.8, 8.2],
  [
    'Q38',
    'air quality testing denver',
    'INFORMATIONAL',
    false,
    'HOME',
    44,
    50,
    2200,
    2450,
    13.6,
    12.8,
  ],
  [
    'Q39',
    'hvac service area denver',
    'INFORMATIONAL',
    false,
    'SERVICE-AREA',
    58,
    64,
    2100,
    2300,
    9.8,
    9.2,
  ],
  [
    'Q40',
    'book hvac appointment online',
    'TRANSACTIONAL',
    false,
    'BOOK',
    68,
    76,
    1900,
    2100,
    6.4,
    5.9,
  ],
].map(
  ([
    key,
    query,
    intent,
    branded,
    landingPageKey,
    priorClicks,
    currentClicks,
    priorImpressions,
    currentImpressions,
    priorPosition,
    currentPosition,
  ]) => ({
    key: String(key),
    query: String(query),
    intent: intent as QueryIntent,
    branded: Boolean(branded),
    landingPageKey: String(landingPageKey),
    priorClicks: Number(priorClicks),
    currentClicks: Number(currentClicks),
    priorImpressions: Number(priorImpressions),
    currentImpressions: Number(currentImpressions),
    priorPosition: Number(priorPosition),
    currentPosition: Number(currentPosition),
  }),
);

/**
 * Month-grain organic clicks for the two pages that carry a narrative.
 *
 * The water-heater guide declined into March, was refreshed on the 9th, and recovered afterwards.
 * Those points are what make the completed outcome measurable rather than asserted.
 */
export const pageMonthlyClicks: Record<string, ReadonlyArray<readonly [string, number]>> = {
  'AC-REPAIR': [
    ['2025-07', 3100],
    ['2025-08', 2850],
    ['2025-09', 2150],
    ['2025-10', 1780],
    ['2025-11', 1520],
    ['2025-12', 1340],
    ['2026-01', 1280],
    ['2026-02', 1410],
    ['2026-03', 1720],
    ['2026-04', 2180],
    ['2026-05', 2940],
    ['2026-06', 3680],
    ['2026-07', 4420],
  ],
  'WATER-HEATER-GUIDE': [
    ['2025-07', 2400],
    ['2025-08', 2280],
    ['2025-09', 2050],
    ['2025-10', 2180],
    ['2025-11', 2320],
    ['2025-12', 2510],
    ['2026-01', 2680],
    ['2026-02', 2210],
    ['2026-03', 2040],
    ['2026-04', 2510],
    ['2026-05', 2690],
    ['2026-06', 2920],
    ['2026-07', 3260],
  ],
};
