/**
 * Post-level social fixtures for Summit & Sage.
 *
 * Platforms do not share a metric vocabulary and this file refuses to pretend they do. Instagram
 * and Facebook report accounts reached; LinkedIn reports impressions and has no reach concept at
 * all, so its posts carry `null` rather than a number invented to fill the column. Engagement rate
 * is therefore computed against a different denominator per platform, which is why it is derived
 * here rather than by one shared formula downstream.
 *
 * Reach is deliberately modelled as non-additive. Weekly reach cannot be summed into monthly reach
 * because the same accounts recur, and the metric definition says so.
 *
 * Account totals exceed the sum of posts published in the same week. Older posts keep being served
 * and profile surfaces contribute too, so a post-level table that added up to the account total
 * would be the implausible outcome.
 */

export type SocialPlatform = 'INSTAGRAM' | 'FACEBOOK' | 'LINKEDIN';

export type SocialFormat = 'REEL' | 'STATIC' | 'CAROUSEL' | 'VIDEO' | 'TEXT' | 'LINK';

/** How each platform's numbers are defined, so no surface silently equates them. */
export const socialPlatforms = [
  {
    platform: 'INSTAGRAM' as const,
    connectionKey: 'meta',
    displayName: 'Instagram',
    reportsReach: true,
    engagementRateBasis: 'REACH' as const,
    note: 'Reach counts unique accounts. Engagement rate is engagements divided by accounts reached.',
  },
  {
    platform: 'FACEBOOK' as const,
    connectionKey: 'meta',
    displayName: 'Facebook',
    reportsReach: true,
    engagementRateBasis: 'REACH' as const,
    note: 'Reach counts unique accounts. Engagement rate is engagements divided by accounts reached.',
  },
  {
    platform: 'LINKEDIN' as const,
    connectionKey: 'linkedin',
    displayName: 'LinkedIn',
    reportsReach: false,
    engagementRateBasis: 'IMPRESSIONS' as const,
    note: 'LinkedIn reports impressions rather than reach. Engagement rate is engagements divided by impressions and is not comparable to a reach-based rate.',
  },
];

export interface SocialPostFixture {
  id: string;
  platform: SocialPlatform;
  publishedOn: string;
  campaignStableKey: string | null;
  pillar: string;
  format: SocialFormat;
  /** Technician-led content is the pattern the account has been leaning into since March. */
  technicianLed: boolean;
  caption: string;
  /** Null on LinkedIn, which does not report reach. */
  reach: number | null;
  impressions: number;
  engagements: number;
  linkClicks: number;
  siteSessions: number;
}

export const socialPosts: SocialPostFixture[] = (
  [
    // Instagram, Aug 2025 to Feb 2026. Static and carousel promotion, modest performance.
    [
      'IG-01',
      'INSTAGRAM',
      '2025-08-12',
      'CAM-02',
      'Seasonal offer',
      'STATIC',
      false,
      'Comfort Club enrolment reminder',
      2100,
      2680,
      84,
      12,
      5,
    ],
    [
      'IG-02',
      'INSTAGRAM',
      '2025-08-26',
      null,
      'Home comfort education',
      'CAROUSEL',
      false,
      'Five signs your AC is struggling',
      1850,
      2340,
      96,
      18,
      8,
    ],
    [
      'IG-03',
      'INSTAGRAM',
      '2025-09-16',
      null,
      'Customer story',
      'STATIC',
      false,
      'A Wash Park furnace rescue',
      1920,
      2410,
      78,
      9,
      4,
    ],
    [
      'IG-04',
      'INSTAGRAM',
      '2025-10-07',
      'CAM-04',
      'Seasonal offer',
      'STATIC',
      false,
      'Book your furnace tune-up',
      2260,
      2890,
      91,
      14,
      6,
    ],
    [
      'IG-05',
      'INSTAGRAM',
      '2025-11-11',
      'CAM-04',
      'Home comfort education',
      'CAROUSEL',
      false,
      'What a furnace inspection covers',
      2480,
      3120,
      118,
      22,
      11,
    ],
    [
      'IG-06',
      'INSTAGRAM',
      '2025-12-09',
      null,
      'Team and craft',
      'STATIC',
      false,
      'Meet Devon, our dispatch lead',
      2050,
      2570,
      102,
      11,
      5,
    ],
    [
      'IG-07',
      'INSTAGRAM',
      '2026-01-20',
      'CAM-04',
      'Home comfort education',
      'CAROUSEL',
      false,
      'Cold snap checklist for Denver homes',
      2740,
      3480,
      126,
      24,
      12,
    ],
    [
      'IG-08',
      'INSTAGRAM',
      '2026-02-17',
      null,
      'Customer story',
      'STATIC',
      false,
      'Same-day heat in Baker',
      2380,
      2960,
      88,
      10,
      5,
    ],

    // March onwards: technician-led short-form video enters the mix and reach steps up.
    [
      'IG-09',
      'INSTAGRAM',
      '2026-03-10',
      'CAM-01',
      'Team and craft',
      'REEL',
      true,
      'Jonah diagnoses a failing capacitor',
      4200,
      5100,
      268,
      31,
      16,
    ],
    [
      'IG-10',
      'INSTAGRAM',
      '2026-03-24',
      null,
      'Home comfort education',
      'STATIC',
      false,
      'Filter sizes explained',
      2520,
      3180,
      94,
      13,
      6,
    ],
    [
      'IG-11',
      'INSTAGRAM',
      '2026-04-14',
      'CAM-01',
      'Team and craft',
      'REEL',
      true,
      'Inside a spring AC tune-up',
      5400,
      6350,
      342,
      44,
      21,
    ],
    [
      'IG-12',
      'INSTAGRAM',
      '2026-04-28',
      'CAM-01',
      'Seasonal offer',
      'STATIC',
      false,
      'Summer Ready booking window open',
      2890,
      3620,
      106,
      12,
      5,
    ],
    [
      'IG-13',
      'INSTAGRAM',
      '2026-05-12',
      'CAM-01',
      'Team and craft',
      'REEL',
      true,
      'Why your condenser needs clearance',
      6800,
      7900,
      431,
      58,
      29,
    ],
    [
      'IG-14',
      'INSTAGRAM',
      '2026-05-26',
      null,
      'Customer story',
      'CAROUSEL',
      false,
      'A Sloan Lake AC replacement',
      3140,
      3950,
      148,
      26,
      13,
    ],

    // The last eight weeks of the reporting window.
    [
      'IG-15',
      'INSTAGRAM',
      '2026-06-16',
      'CAM-01',
      'Team and craft',
      'REEL',
      true,
      'Elena walks a heat-pump swap',
      8200,
      9400,
      512,
      71,
      38,
    ],
    [
      'IG-16',
      'INSTAGRAM',
      '2026-06-23',
      'CAM-01',
      'Seasonal offer',
      'STATIC',
      false,
      'Beat the heat wave promotion',
      3260,
      4180,
      112,
      14,
      6,
    ],
    [
      'IG-17',
      'INSTAGRAM',
      '2026-06-30',
      null,
      'Home comfort education',
      'CAROUSEL',
      false,
      'Thermostat settings that actually help',
      4200,
      5300,
      168,
      29,
      15,
    ],
    [
      'IG-18',
      'INSTAGRAM',
      '2026-07-07',
      'CAM-01',
      'Team and craft',
      'REEL',
      true,
      'Jonah on the one AC noise to never ignore',
      8800,
      10100,
      548,
      78,
      41,
    ],
    [
      'IG-19',
      'INSTAGRAM',
      '2026-07-14',
      'CAM-01',
      'Seasonal offer',
      'STATIC',
      false,
      'Same-day AC repair availability',
      3480,
      4420,
      118,
      15,
      6,
    ],
    [
      'IG-20',
      'INSTAGRAM',
      '2026-07-21',
      'CAM-01',
      'Team and craft',
      'REEL',
      true,
      'A technician’s two-minute duct check',
      9100,
      10500,
      587,
      84,
      44,
    ],
    [
      'IG-21',
      'INSTAGRAM',
      '2026-07-28',
      'CAM-01',
      'Home comfort education',
      'CAROUSEL',
      false,
      'What happens after you book',
      4800,
      6000,
      186,
      33,
      17,
    ],

    // Facebook: steady local awareness, consistently weaker downstream traffic.
    [
      'FB-01',
      'FACEBOOK',
      '2025-09-09',
      null,
      'Home comfort education',
      'LINK',
      false,
      'Furnace safety before winter',
      3400,
      4200,
      92,
      28,
      9,
    ],
    [
      'FB-02',
      'FACEBOOK',
      '2025-11-18',
      'CAM-04',
      'Seasonal offer',
      'STATIC',
      false,
      'Cold Snap Ready service reminder',
      3620,
      4480,
      104,
      22,
      7,
    ],
    [
      'FB-03',
      'FACEBOOK',
      '2026-01-13',
      'CAM-04',
      'Home comfort education',
      'LINK',
      false,
      'Ice dams and your heating system',
      3810,
      4700,
      98,
      31,
      10,
    ],
    [
      'FB-04',
      'FACEBOOK',
      '2026-02-24',
      null,
      'Customer story',
      'STATIC',
      false,
      'A Highlands water-heater swap',
      3520,
      4340,
      88,
      18,
      6,
    ],
    [
      'FB-05',
      'FACEBOOK',
      '2026-04-07',
      'CAM-01',
      'Seasonal offer',
      'STATIC',
      false,
      'Spring AC tune-up scheduling',
      3740,
      4620,
      96,
      20,
      7,
    ],
    [
      'FB-06',
      'FACEBOOK',
      '2026-05-19',
      'CAM-01',
      'Home comfort education',
      'LINK',
      false,
      'Repair or replace your AC?',
      3980,
      4900,
      108,
      34,
      11,
    ],
    [
      'FB-07',
      'FACEBOOK',
      '2026-06-09',
      'CAM-01',
      'Seasonal offer',
      'STATIC',
      false,
      'Summer Ready appointment slots',
      4060,
      5010,
      102,
      21,
      7,
    ],
    [
      'FB-08',
      'FACEBOOK',
      '2026-06-23',
      null,
      'Customer story',
      'VIDEO',
      false,
      'A Park Hill install, start to finish',
      4240,
      5220,
      134,
      26,
      9,
    ],
    [
      'FB-09',
      'FACEBOOK',
      '2026-07-14',
      'CAM-01',
      'Home comfort education',
      'LINK',
      false,
      'How Denver heat affects your AC',
      4180,
      5150,
      112,
      36,
      12,
    ],
    [
      'FB-10',
      'FACEBOOK',
      '2026-07-28',
      'CAM-01',
      'Seasonal offer',
      'STATIC',
      false,
      'Heat advisory service availability',
      4320,
      5340,
      106,
      19,
      6,
    ],

    // LinkedIn: employer brand and recruiting. No reach metric exists for these rows.
    [
      'LI-01',
      'LINKEDIN',
      '2025-10-14',
      null,
      'Recruiting',
      'TEXT',
      false,
      'We are hiring service technicians',
      null,
      2400,
      68,
      14,
      4,
    ],
    [
      'LI-02',
      'LINKEDIN',
      '2025-12-02',
      null,
      'Team and craft',
      'STATIC',
      false,
      'Our apprenticeship programme',
      null,
      2180,
      74,
      11,
      3,
    ],
    [
      'LI-03',
      'LINKEDIN',
      '2026-02-10',
      null,
      'Recruiting',
      'TEXT',
      false,
      'What a ride-along day looks like',
      null,
      2620,
      82,
      18,
      5,
    ],
    [
      'LI-04',
      'LINKEDIN',
      '2026-04-21',
      null,
      'Recruiting',
      'STATIC',
      false,
      'Now hiring dispatch coordinators',
      null,
      2840,
      91,
      16,
      4,
    ],
    [
      'LI-05',
      'LINKEDIN',
      '2026-06-02',
      null,
      'Team and craft',
      'STATIC',
      false,
      'Eighty-six people, one service promise',
      null,
      3050,
      96,
      13,
      4,
    ],
    [
      'LI-06',
      'LINKEDIN',
      '2026-07-07',
      null,
      'Recruiting',
      'TEXT',
      false,
      'Why our technicians stay',
      null,
      3280,
      104,
      21,
      6,
    ],
    [
      'LI-07',
      'LINKEDIN',
      '2026-07-28',
      null,
      'Recruiting',
      'STATIC',
      false,
      'Summer hiring for the autumn season',
      null,
      3420,
      112,
      19,
      5,
    ],
  ] as const
).map(
  ([
    id,
    platform,
    publishedOn,
    campaignStableKey,
    pillar,
    format,
    technicianLed,
    caption,
    reach,
    impressions,
    engagements,
    linkClicks,
    siteSessions,
  ]) => ({
    id,
    platform,
    publishedOn,
    campaignStableKey,
    pillar,
    format,
    technicianLed,
    caption,
    reach,
    impressions,
    engagements,
    linkClicks,
    siteSessions,
  }),
);

/**
 * Start of the trailing eight-week window used for pattern comparisons.
 *
 * Fixed rather than derived from the current date so the published demonstration says the same
 * thing every time it is opened.
 */
export const SOCIAL_RECENT_WINDOW_START = '2026-06-08';
